#ifndef DEFINES_H
#define DEFINES_H

#define PIXEL_SCALE 10
#define CHIP8_PIXEL_WIDTH 64
#define CHIP8_PIXEL_HEIGHT 32
#define SCREEN_WIDTH (CHIP8_PIXEL_WIDTH * PIXEL_SCALE)
#define SCREEN_HEIGHT (CHIP8_PIXEL_HEIGHT * PIXEL_SCALE)
#define PIXEL_COUNT (CHIP8_PIXEL_WIDTH * CHIP8_PIXEL_HEIGHT)

#endif //DEFINES_H